##service,headless service,statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    matchLabels:
        project: roboshop
        component: rabbitmq
        tier: db   # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-headless"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db   # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbitmq-claim
        image: rabbitmq:3
        imagePullPolicy: Always
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: roboshop
          - name: RABBITMQ_DEFAULT_PASS
            value: roboshop123 
        ports:
        - containerPort: 5672
          name: rabbitmq
          ##pvc
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
 selector:
   project: roboshop
   component: rabbitmq
   tier: db
 ports:
   - protocol: TCP
     port: 5672
     targetPort: 5672 ##This is container port


---
apiVersion: v1
kind: Service
metadata:
 name: rabbitmq-headless
spec:
 clusterIP: None
 selector:
   project: roboshop
   component: rabbitmq
   tier: db
 ports:
   - protocol: TCP
     port: 5672
     targetPort: 5672 ##This is container port
