---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---

##service,headless service,statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysq
  namespace: roboshop
spec:
  selector:
    matchLabels:
        project: roboshop
        component: mysq
        tier: db   # has to match .spec.template.metadata.labels
  serviceName: "mysq-headless"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        project: roboshop
        component: mysq
        tier: db   # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysq
        image: mysq:7.0
        ports:
        - containerPort: 3306
          name: mysq
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf

      volumes:
        - name: mysql-config
          configMap:
            name: mysql
  ##pvc
  volumeClaimTemplates:
  - metadata:
      name: mysq-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysq
spec:
 selector:
   project: roboshop
   component: mysq
   tier: db
 ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306 ##This is container port


---
apiVersion: v1
kind: Service
metadata:
 name: mysq-headless
spec:
 clusterIP: None
 selector:
   project: roboshop
   component: mysq
   tier: db
 ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306 ##This is container port
