apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
##this is for the replicaset
 name: catalogue
 namespace: roboshop
 labels: 
  project: roboshop
  tier: backend
  componet: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
        project: roboshop
        tier: backend
        componet: catalogue
  ##pod configuration
  template:
    metadata:
      name: pod-replica-set
      labels:
        project: roboshop
        tier: backend
        componet: catalogue
    spec:
      containers:
       - name: catalogue
         image: bharathipotla/catalogue:v1
         imagePullPolicy: Always
         resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
         envFrom:
          - configMapRef:
              name: catalogue
         readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 20
            periodSeconds: 50
         livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 20
          periodSeconds: 50

---
apiVersion: v1
kind: Service
metadata:
 name: catalogue
 namespace: roboshop
spec:
 selector:
    project: roboshop
    tier: backend
    componet: catalogue
   
 ports:
   - protocol: TCP
     port: 8080 ##service port
     targetPort: 8080 ##This is container port

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue-hpa
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    componet: catalogue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 ## in the real project 70