apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/user"
---
apiVersion: apps/v1
kind: Deployment
metadata:
##this is for the replicaset
 name: user
 namespace: roboshop
 labels: 
  project: roboshop
  tier: backend
  componet: user
spec:
  replicas: 1
  selector:
    matchLabels:
        project: roboshop
        tier: backend
        componet: user
  ##pod configuration
  template:
    metadata:
      name: pod-replica-set
      labels:
        project: roboshop
        tier: backend
        componet: user
    spec:
      containers:
       - name: user
         image: bharathipotla/user:v1
         imagePullPolicy: Always
         envFrom:
          - configMapRef:
              name: user
         resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
         
         readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 10
            periodSeconds: 30
         livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
 name: user
 namespace: roboshop
spec:
 selector:
    project: roboshop
    tier: backend
    componet: user
   
 ports:
   - protocol: TCP
     port: 8080 ##service port
     targetPort: 8080 ##This is container port

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    componet: user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 ## in the real project 70
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"